### ISSUE TITLE
Swift compatible version issue

### ISSUE THREAD

**Issue by tapan-nathvani** [digio-in/digio-ios-sdk#1]
I am getting an error in XCode 13.3

Module compiled with Swift 5.5 cannot be imported by the Swift 5.6 compiler: /Users/username/Documents/ProjectName-iOS/digio-ios-sdk-0.0.2/DigioEsignSDK.framework/Modules/DigioEsignSDK.swiftmodule/arm64-apple-ios.swiftmodule

**Comment by akashdigio** [comment]
Hi Tapan,

Please use SDK version 0.0.4
