### ISSUE TITLE
Errors while compiling in simulator

### ISSUE THREAD

**Issue by tapan-nathvani** [digio-in/digio-ios-sdk#2]
Hi,

I am trying to run project in iPhone 13 pro simulator with xcode 13.3 but receiving an error like

Could not find module 'DigioEsignSDK' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios, at: /Users/username/Documents/Project-iOS/digio-ios-sdk-0.0.2/DigioEsignSDK.framework/Modules/DigioEsignSDK.swiftmodule

**Comment by akashk2512** [comment]
@tapan-nathvani This SDK supports the only physical devices. Simulator version is not supported

**Comment by tapan-nathvani** [comment]
is there any way to check on all the simulators?

**Comment by akashdigio** [comment]
You can write support@digio.in with your official mail id.
